baseURL: 'https://hortlund.github.io'
languageCode: en-us
title: Cloudbot
theme: PaperMod
  #f
params:
    ShowReadingTime: true
    homeInfoParams:
        Title: Hi there, I'm Andreas Hortlund
        Content: Software Engineer, DevOps, Security

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/Hortlund"
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/andreas-hortlund-245482121/"
    ShowToc: true
    ShowCodeCopyButtons: true
    author: ["Andreas"]
    ShowPostNavLinks: true
